# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf35cf8aa2cdea759d470919644e12123098c93d922e78d3e3a4e711587d2517bab434b1cb975eb196b34e828e47ad00092966e9fa71000b00fc94930a767f40

test:
  secret_key_base: 655ee44e30f9b10e51a217577d3720d0ce501571f889d5834917c085cd029795bafe1bb4b298e6764b90b523b1360114d6bccc8239d3ec83b623b667b3bbabc0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
