# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60e65d82c36640d7c57bf548e02862e815a63ea1eae9266edb7ac6aac553d51281c4660b0a5bb246197070e9ef230e05894b326862b6447faaed887f552b2dfa

test:
  secret_key_base: 338f768cb9c7ac8e23650917d7eea2a96bc132ad5eb9aa614d0cdbd1ee552966268583bbf62af84f6330668b3ed48ce42ac2fbc624c7069422c40a253fd9cc7a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
