# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c36363dd75958e9c9c00ee4b7e2bc60e3b29a0c5859b85c3925435ab2783909433f954059f609ef6985b58ddeddc147dec4adfc490d1cad36aad5a22e8f33ec

test:
  secret_key_base: 6dc4c68b6c853db8315ff73cf682494fc618c628265eeebbc32822747aa8c61fa37bf3a1f4f686dce64dfddbafa62708a3d89907f4694951eca68d749d026080

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
