# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 17a3523a4122dc7cc375ce98a54b93235efbd48efb44575beec0911cc251fef789953dca790cbce8c93324ff8815033fa245113e499e20e8f95e38e68964b352

test:
  secret_key_base: e48619fc67cf426af34e4443f404a3569384718a55f013b7ec4cf7b9b6dd6456ec13bd8e4555592d60c9439ad374cbd497f86a44f98c4a8b93206a3ade37b68b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
